### PR TITLE
Move NPM to published and add version

### PR DESCRIPTION
**Pull request by jeffmendoza**
Releasing as described in process.md

### CODE REVIEW

**Comment by laurentsimon** [comment]
@lirantal, @soldair, @ljharb this is the final PR to release the v1 version of the doc. Thank you so much for all your feedback and the discussion. None of this would have been possible without your help.

We would like to officially release this doc via a short blog post under the OpenSSF. Would you be interested in helping out review and / or co-authoring?

**Comment by ljharb** [comment]
Happy to!

**Comment by lirantal** [comment]
Happy to join that as well!

**Comment by erezrokah** [comment]
Yes please 😄 Thank you for the mention, happy to join!

**Comment by ran-dall** [comment]
@jeffmendoza I've been reading the guide in detail several times today, collaborating on the blog article. I found some various minor grammatical errors, so would you mind if I gave it a proofread?

**Comment by laurentsimon** [comment]
Please go ahead @ran-dall Appreciate the help!

**Comment by feelepxyz** [comment]
@jeffmendoza the `Signing and Verification` section could be updated:

PGP signatures have been deprecated in favour of ECDSA signatures on the official npm registry.

These new registry signatures can be verified by running `npm audit signatures`. We recommend this to be run after install on CI.

**Comment by jeffmendoza** [comment]
@feelepxyz Please open up an issue. As this would be a recommendation change (not typo/grammar), we need a chance for community input. Thanks!

**Pull request merged**
